#
# Local site settings
remote_theme: wet-boew/gcweb-jekyll
title: "GCWeb, the Canada.ca official theme" # Site name or title
website: "https://wet-boew.github.io/GCWeb/" # URL of your public facing website
global:
  lang: fr
  feedbackPath:
    en: "/sites/feedback/ajax/report-problem-en.html"
    fr: "/sites/feedback/ajax/report-problem-fr.html"
  contextualFooter: # Contextual footer settings
    title:
      en: "[Contextual footer title]"
      fr: "[Titre du menu contextuel]"
    links: # List of links visible in the contextual footer
      fr:
        - url: "http://canada.ca/fr"
          text: "Lien 1"
        - url: "http://canada.ca/fr"
          text: "Lien 2"
        - url: "http://canada.ca/fr"
          text: "Lien 3"
      en:
        - url: "http://canada.ca/en"
          text: "Link 1"
        - url: "http://canada.ca/en"
          text: "Link 2"
        - url: "http://canada.ca/en"
          text: "Link 3"

#
# Page front matter defaults
defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default

#
# Collections
collections:
  wetboew-demos:
    output: true
#    permalink: /wet-boew-demos/:name

#
# Jekyll settings
timezone: America/Toronto # Timezone for blog posts and alike
#verbose: true
#quiet: false
sass:
  sass_dir: "sites"
#  load_paths: [
#    "node_modules" # we might only need bootstrap scss
#  ,
#    "node_modules/wet-boew/node_modules" # todo: find a way to include it.
#  ]

#
# Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE*
- SECURITY.md
- Gruntfile.coffee
- CNAME
- "*.tmp"
- Gemfile
- Gemfile.lock
- gcweb-jekyll.gemspec
- .jekyll-cache
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
